runtime: go120

env_variables:
  DB_USER: postgres
  DB_PASSWORD: EfeL@Piedra99..
  DB_NAME: pronaces
  INSTANCE_CONNECTION_NAME: pronaces-survey-392823:us-central1:pronaces-storage1
  PRIVATE_IP: 35.223.146.187
  DB_PORT: 5432
  PORT: 8080

handlers:
- url: /.*
  script: _go_app
