runtime: go120

env_variables:
  DB_NAME: pronaces
  DB_USERNAME: postgres
  DB_PASSWORD: EfeL@Piedra99..
  DB_HOST: 35.223.146.187
  DB_PORT: 5432
  PORT: 8080

handlers:
- url: /.*
  script: _go_app
  