server:
  domain: "http://localhost:4000"
  port: 4000

database:
  host: "localhost"
  port: 5432
  name: "pronaces"
  user: "postgres"
  password: "root"
  migrate: true
  seed: true

token:
  access_token: "pronaces@2023_token"